databases: # Render PostgreSQL database
  - name: sprestage-portfolio-db
    databaseName: portfolio_production_db
    ipAllowList: [] # only allow internal connections

services:
  - type: web # valid values: https://render.com/docs/yaml-spec#type
    name: sprestage-portfolio
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free # optional; defaults to starter
    numInstances: 1
    domains: # custom domains
      - 'myportfolio.sprestage.com'
      - 'portfolio.sprestage.com'
      - 'sprestage.com'
      - 'www.sprestage.com'
    envVars:
      - key: LANG # Imported from Heroku app
        value: en_US.UTF-8
      - key: RACK_ENV # Imported from Heroku app
        value: production
      - key: RAILS_ENV # Imported from Heroku app
        value: production
      - key: RAILS_LOG_TO_STDOUT # Imported from Heroku app
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES # Imported from Heroku app
        value: enabled
      - key: DATABASE_URL # Render PostgreSQL database
        fromDatabase:
          name: sprestage-portfolio-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
